language: python
install:
  - wget -O- http://neuro.debian.net/lists/bionic.de-m.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
  - sudo apt update
  - sudo apt install singularity-container
  - pip install tox
dist: bionic
python: 3.5  # Use the oldest supported version of python as default.
script:
    - tox -e $TOX_ENV
matrix:
  include:
    - env: TOX_ENV=lint
    # UNIT TESTS
    # On most recent versions of python.
    - env: TOX_ENV=py35
      install:
        - pip install codecov
        - pip install tox
      after_success:
        - codecov -v  # -v to make sure coverage upload works.
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
